version: "3.7"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB_NAME=library
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=5000
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:4.4 # Changed to MongoDB 4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:

